ifndef PSIMAKEFILE
PSIMAKEFILE=/ioc/tools/driver.makefile
endif

include $(PSIMAKEFILE)
include $(EPICS_MODULES)/makeUtils/latest/utils.mk

# don't use a general wildcard -- we don't want to install this makefile ;-)
QT=*.ui *.jpeg
